CUDA_VISIBLE_DEVICES=3 nohup python scripts/train_test.py \
--model_type pretrained-transformers-pooling \
--pretrained_name gpt2  \
--batch_size 32 \
--evaluate True \
--learning_rate 5e-5 \
--use_cuda True \
--scheduler True \
--num_epochs 5 \
--early_stopping 3 \
--num_warming_steps 0.1 \
--n_gpu 1 \
--grad_norm_clip 0.5 \
